# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebebf74aa8788c17fdabdc9d08195a5d7ed6d01523a4b11b08f17b1332db5b898b707c936acab11967610ed0a505262eef8c412d142cfb4d9145d151e33eb583

test:
  secret_key_base: 17962408e57778db0285b441d41d45cc84394683e27a2f48e611ce9d76828a57c3ba79640307b4cf29ca30d6a1be02995a9f89f6f2c52bbcc243c2e5be8b2f35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
